version: "3"
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment: 
      MONGO_URL: "mongodb://mongo:27017/currency_converter"
    depends_on:
      - mongo
    links: 
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
